"""empty message

Revision ID: 54a72c2343f7
Revises: 
Create Date: 2019-11-07 03:22:05.930592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a72c2343f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titanic',
    sa.Column('PassengerId', sa.Float(), nullable=False),
    sa.Column('Survived', sa.Float(), nullable=True),
    sa.Column('Pclass', sa.Float(), nullable=True),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Sex', sa.String(length=10), nullable=True),
    sa.Column('Age', sa.Float(), nullable=True),
    sa.Column('SibSp', sa.Float(), nullable=True),
    sa.Column('Parch', sa.Float(), nullable=True),
    sa.Column('Ticket', sa.String(length=20), nullable=True),
    sa.Column('Fare', sa.Float(), nullable=True),
    sa.Column('Cabin', sa.String(length=20), nullable=True),
    sa.Column('Embarked', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('PassengerId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titanic')
    # ### end Alembic commands ###
